export enum RequestStatus {
    IN_REVIEW = 'IN REVIEW',
    IN_QA_VERIFICATION = 'IN QA VERIFICATION',
    IN_QA_APPROVAL = 'IN QA APPROVAL',
    IN_PERF = 'IN PERF',
    IN_PRE_PROD = 'IN PRE PROD',
    IN_PROD = 'IN PROD'
} 